/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-30 03:34:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class adm_005fte_005fwait_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  int i=1; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    \t<link href=\"bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"JQuery/jquery-3.2.1.js\"></script>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("        <script>\r\n");
      out.write("         javascript:window.history.forward(1);   \r\n");
      out.write("        </script>\r\n");
      out.write("         <script>\r\n");
      out.write("            function fi()\r\n");
      out.write("    {\r\n");
      out.write("    parent.location='adm_hm.jsp'\r\n");
      out.write("    }\r\n");
      out.write("         </script> \r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"container\">\r\n");
      out.write("        ");
 
        HttpSession ad=request.getSession();
        String v=(String)ad.getAttribute("aus");
         
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h3>Loginby:");
      out.print( v );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"adm_hm.jsp\">Home</a>&nbsp;<a href=\"adm_logout.jsp\">Logout</a></h3>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <h2 align=\"center\"><font size=\"6\" color=\"#800080\">List of Requests by Teachers</font></h2>\r\n");
      out.write("\t\t<p align=\"center\">&nbsp;</p>\r\n");
      out.write("        <form name=\"f1\" action=\"adm_te_accept_in\" method=\"POST\">\r\n");
      out.write("        <div align=\"center\">\r\n");
      out.write("        <table class=\"table table-striped table-condensed\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">S No.</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">Teacher User Name</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">Teacher First Name</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">Teacher Last Name</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">Phone No.</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">Address</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">E mail id</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">Course Registered</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">No.of Question in Exam</font></th>\r\n");
      out.write("<th bgcolor=\"#FF9933\"><font color=\"#FFFFFF\" size=\"4\">Password</font></th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");

    String s1=null;
    String s2=null;
    String s3=null;
    String s4=null;
    String s5=null;
    String s6=null;
    String s7=null;
    long p=0;
    long j=0;
    try
        {
     Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
     Connection conn = DriverManager.getConnection("jdbc:odbc:ac");
     Statement stat = conn.createStatement();
     String g = "select * from wait_te";
     ResultSet rs = stat.executeQuery(g);
     while (rs.next())
     {
            s1=rs.getString("f_name");
            s2=rs.getString("u_name");
            s3=rs.getString("c_adp");
            s4=rs.getString("l_name");
            s5=rs.getString("e_id");
            s6=rs.getString("addr");
            s7=rs.getString("password");
            p=rs.getInt("phone");
            j=rs.getInt("no_ques");
            ad.setAttribute("cs", s3);

      out.write("      \r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(i);
      out.write("</td>\r\n");
      out.write("<td><input type=\"radio\" name=\"g1\" value=\"");
      out.print( s2 );
      out.write("\" />");
      out.print( s2 );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s1);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s4);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(p);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s6);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s5);
      out.write("</td>\r\n");
      out.write("<td><input type=\"hidden\" name=\"t1\" value=\"");
      out.print(s3);
      out.write("\" />");
      out.print(s3);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(j);
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(s7);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

i++;
} 
i=1;
     
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p align=\"center\">\r\n");

}
catch(Exception ae)
{
    System.out.println("OOPs ERROR!!");
ae.printStackTrace();
}               

      out.write(" \r\n");
      out.write("<br>\r\n");
      out.write("<h4>\r\n");
      out.write("<input type=\"radio\" name=\"g2\" value=\"accept\" />To accept the Teacher\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"radio\" name=\"g2\" value=\"reject\" />To reject the Teacher\r\n");
      out.write("</h4>\r\n");
      out.write("<br>       \r\n");
      out.write("  \r\n");
      out.write("<input class=\"btn btn-link\" type=\"submit\" value=\">>Back\" name=\"b2\" onClick=\"fi()\" style=\"font-weight: 700\" />\r\n");
      out.write("<input class=\"btn btn-success\"  type=\"submit\" value=\"Accept\" name=\"b1\" style=\"font-weight: 700\" />\r\n");
      out.write("</p>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
