/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-30 03:48:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class amd_005fcs_005fmd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    \t<link href=\"bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"JQuery/jquery-3.2.1.js\"></script>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>JSP Page</title>\r\n");
      out.write("        <script language=\"javascript\">\r\n");
      out.write("         javascript:window.history.forward(1);   \r\n");
      out.write("        </script>\r\n");
      out.write("        <script language=\"javascript\">\r\n");
      out.write("function check()\r\n");
      out.write("{\r\n");
      out.write("var txtAD;\r\n");
      out.write("txtAD = document.getElementById('t4');\r\n");
      out.write("var txtAD1 = document.getElementById('t6');\r\n");
      out.write(" if (txtAD.value == '') //if(name.value=='')\r\n");
      out.write("{\r\n");
      out.write("alert(\"Enter the Minimum No of Question\");\r\n");
      out.write("return false;\r\n");
      out.write("}    \r\n");
      out.write("if (txtAD1.value == '') //if(name.value=='')\r\n");
      out.write("{\r\n");
      out.write("alert(\"Enter the Maximum No of Question\");\r\n");
      out.write("return false;\r\n");
      out.write("}    \r\n");
      out.write("}\r\n");
      out.write("</script> \r\n");
      out.write("        <script>\r\n");
      out.write("function fi()\r\n");
      out.write("    {\r\n");
      out.write("    parent.location='adm_hm.jsp'\r\n");
      out.write("    }\r\n");
      out.write("</script> \r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"container\">\r\n");
 
        HttpSession ad=request.getSession();
        String s1=(String)ad.getAttribute("aus");
         
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h3>Loginby:");
      out.print( s1 );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"adm_hm.jsp\">Home</a>&nbsp;<a href=\"adm_logout.jsp\">Logout</a></h3>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <h2><font color=\"#800080\"><span style=\"font-size: 20pt\">Modify the Course</span></font></h2> \r\n");
      out.write("        <form name=\"f1\" action=\"adm_cs_md_in\" method=\"POST\">\r\n");
      out.write("      <b>\r\n");
      out.write("      ");

      System.out.println("Course Selected to modify");
      String cs=request.getParameter("d1");      
      
      out.write("</b><font size=\"4\"><b>Course Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t</b> \r\n");
      out.write("\t\t<input name=\"t2\" value=\"");
      out.print( cs );
      out.write("\" readonly=\"readonly\" style=\"font-weight: 700\" /><b>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("      ");

      
     String s9=null;
     String s8=null;
     String s10=null;
        try
{
Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
Connection conn=DriverManager.getConnection("jdbc:odbc:ac");
Statement stat=conn.createStatement();
String str="select * from course where c_name='"+cs+"'";
ResultSet rs= stat.executeQuery(str);
while (rs.next())
     {
    s9=rs.getString("c_id");
    s8=rs.getString("ques_disp");
    s10=rs.getString("max_q");
    
      out.write("Course Id&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;\r\n");
      out.write("\t\t</b> \r\n");
      out.write("\t\t<input name=\"t1\" value=\"");
      out.print( s9 );
      out.write("\" readonly=\"readonly\" style=\"font-weight: 700\" /><b>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\t\tMax No of Question in Exam Paper&nbsp;&nbsp;&nbsp; </b> \r\n");
      out.write("\t\t<input name=\"t3\" value=\"");
      out.print( s8 );
      out.write("\" readonly=\"readonly\" style=\"font-weight: 700\" /><b>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\t\tMax No of Question in Exam Paper&nbsp;&nbsp;&nbsp; </b> \r\n");
      out.write("\t\t<input name=\"t5\" value=\"");
      out.print( s10 );
      out.write("\" readonly=\"readonly\" style=\"font-weight: 700\" /><b>\r\n");
  
}  
}
catch(Exception ae)
{}               

      out.write("  \r\n");
      out.write("<br>\r\n");
      out.write("\t\t</b></font><b>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("    \t</b>\r\n");
      out.write("    <h2><font color=\"#800080\"><span style=\"font-size: 20pt\">Enter the New Value</span></font></h2>\r\n");
      out.write("\t\t<b>\r\n");
      out.write("<br>\r\n");
      out.write("\t\t</b><font size=\"4\"><b>Min No of Question in Exam Paper&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t</b> <input name=\"t4\" id=\"t4\" style=\"font-weight: 700\" /><b> </b></font>\r\n");
      out.write("                 <br>\r\n");
      out.write("                 <font size=\"4\"><b>Max No of Question in Exam Paper&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t</b> <input name=\"t6\" id=\"t6\" style=\"font-weight: 700\" /><b> </b></font>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("<b>\r\n");
      out.write("<br>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("</b>\r\n");
      out.write("<input class=\"btn btn-success\" type=\"submit\" value=\"Submit\" name=\"b1\" onclick=\"return check()\" style=\"font-weight: 700\" />\r\n");
      out.write("<input class=\"btn btn-danger\"  type=\"submit\" value=\"Cancel\" name=\"b2\" onclick=\"fi()\" style=\"font-weight: 700\" />\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<b>\r\n");
      out.write("</b>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
