/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-30 16:14:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import Dbean.Dao;

public final class exam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

   static int x=1,b=0;  


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("        <head>  \r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"JQuery/jquery-3.2.1.js\">\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"bootstrap-3.3.7-dist/js/bootstrap.min.js\">\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<link href=\"bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t\t\t<link href=\"css/exam.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("            <style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-color: #FF9;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    ");
  
    HttpSession st=request.getSession(false);
    LinkedList answers=new LinkedList();
      answers=(LinkedList)st.getAttribute("answers");
      System.out.print(answers);
     // String convert=(String)mysession.getAttribute("No_of_questions");
     // b=Integer.parseInt(convert);
      b=(Integer)st.getAttribute("No_of_questions");
      System.out.println("no of ques deep "+b);
      String cou=(String)st.getAttribute("cs");
      System.out.println("No offf");
      System.out.println(b);
      x=(Integer)st.getAttribute("x");
      System.out.println("its should b 1");
      System.out.println(x);
    String mins = request.getParameter( "mins" );  
    if( mins == null ) mins = "1";  
       
    String secs = request.getParameter( "secs" );  
    if( secs == null ) secs = "1";  
    
      out.write("  \r\n");
      out.write("    <script>  \r\n");
      out.write("   <!--  \r\n");
      out.write("   var mins = ");
      out.print(mins);
      out.write("; // write mins to javascript  \r\n");
      out.write("   var secs = ");
      out.print(secs);
      out.write("; // write secs to javascript  \r\n");
      out.write("   function timer()  \r\n");
      out.write("   {  \r\n");
      out.write("   // tic tac  \r\n");
      out.write("   if( --secs == -1 )  \r\n");
      out.write("   {  \r\n");
      out.write("   secs = 59;  \r\n");
      out.write("   --mins;  \r\n");
      out.write("   }  \r\n");
      out.write("     \r\n");
      out.write("   // leading zero? formatting  \r\n");
      out.write("   if( secs < 10 ) secs = \"0\" + secs;               \r\n");
      out.write("   if( mins < 10 ) mins = \"0\" + parseInt( mins, 10 );  \r\n");
      out.write("     \r\n");
      out.write("   // display  \r\n");
      out.write("   document.forma.mins.value = mins;   \r\n");
      out.write("   document.forma.secs.value = secs; \r\n");
      out.write("        \r\n");
      out.write("   // continue?  \r\n");
      out.write("   if( secs == 0 && mins == 0 ) // time over  \r\n");
      out.write("   {  \r\n");
      out.write("   document.forma.ok.disabled = true;  \r\n");
      out.write("   document.formb.results.style.display = \"block\";  \r\n");
      out.write("   }  \r\n");
      out.write("   else // call timer() recursively every 1000 ms == 1 sec  \r\n");
      out.write("   {  \r\n");
      out.write("   window.setTimeout( \"timer()\", 1000 );  \r\n");
      out.write("   }  \r\n");
      out.write("   }  \r\n");
      out.write("   //-->  \r\n");
      out.write("   </script></head>  \r\n");
      out.write("   \r\n");
      out.write("   ");
 
   
   String s1=null;
            String s2=null;
            String s3=null;
            String s4=null;
            String s5=null;
            String s6=null;           
 //         String str1=null;
            Connection conn=null;
           int p=0;
try
{
conn=Dao.getCon();
Statement stat=conn.createStatement();
String g1 = "select q_id from ques_in where c_name='"+cou+"' ";
  ResultSet rs = stat.executeQuery(g1);
//for storing d qu num from ques table
                 
String str="select * from ques_in where q_id='"+ x + "' and c_name='"+cou+"' ";
     rs= stat.executeQuery(str);
System.out.println(b+"deep "+x);
while (rs.next()  && x<=b)
{

s1=rs.getString("question");
s2=rs.getString("choice1");
s3=rs.getString("choice2");
s4=rs.getString("choice3");
s5=rs.getString("choice4");
s6=rs.getString("ans");

if(x<b)
{      
   
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <body class=\"container\">  \r\n");
      out.write("   <form action=\"exam.jsp\" name=\"forma\" onsubmit=\"go()\">   \r\n");
      out.write("   <br>Time remaining: <input type=\"text\" name=\"mins\" size=\"1\" style=\"border:0px solid black;text-align:right\">:<input type=\"text\" name=\"secs\" size=\"1\" style=\"border:0px solid black\">  \r\n");
      out.write("   <hr>  \r\n");
      out.write("   <label> Question:");
      out.print( x );
      out.write("</label>\r\n");
      out.write("\r\n");
      out.write("<h3>\r\n");
      out.write("<label>");
      out.print( s1 );
      out.write("</label>\r\n");
      out.write("</h3>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<h3>\r\n");
      out.write("Choice1:<input type=radio name=rg value=a >");
      out.print( s2 );
      out.write("</input>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("Choice2:<input type=radio name=rg value=b>");
      out.print( s3 );
      out.write("</input>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("Choice3:<input type=radio name=rg value=c>");
      out.print( s4 );
      out.write("</input>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("Choice4:<input type=radio name=rg value=d>");
      out.print( s5 );
      out.write("</input>\r\n");
      out.write("</h3>\r\n");
      out.write("\t<!-- <input class=\"btn btn-info\" type=\"submit\" name=\"ok\" value=\">>Back\"> -->\r\n");
      out.write("   <input class=\"btn btn-success\" type=\"submit\" name=\"ok\" value=\"Next\">\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("   </form>  \r\n");
      out.write("   <hr>  \r\n");
      out.write("    \r\n");
      out.write("   ");
 
   x++;
   System.out.println("deep Value" +"::::"+x);
   answers.add(request.getParameter("rg"));
   
   st.setAttribute("answers",answers);
  // String gt=Integer.toString(x);
   st.setAttribute("x",x);
   }
else if(x==b)
    {

      out.write("\r\n");
      out.write("<form action=\"result.jsp\" name=\"forma\">  \r\n");
      out.write("  Time remaining: <input type=\"text\" name=\"mins\" size=\"1\" style=\"border:0px solid black;text-align:right\">:<input type=\"text\" name=\"secs\" size=\"1\" style=\"border:0px solid black\">  \r\n");
      out.write("   <hr>  \r\n");
      out.write("   \r\n");
      out.write(" <div id=\"qustionDiv\">\r\n");
      out.write("   \r\n");
      out.write("   <label> Question:");
      out.print( x );
      out.write("</label>\r\n");
      out.write("\r\n");
      out.write("<h3>\r\n");
      out.write("<label>");
      out.print( s1 );
      out.write("</label>\r\n");
      out.write("</h3>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<h3>\r\n");
      out.write("Choice1:<input type=radio name=rg value=a >");
      out.print( s2 );
      out.write("</input>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("Choice2:<input type=radio name=rg value=b>");
      out.print( s3 );
      out.write("</input>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("Choice3:<input type=radio name=rg value=c>");
      out.print( s4 );
      out.write("</input>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("Choice4:<input type=radio name=rg value=d>");
      out.print( s5 );
      out.write("</input>\r\n");
      out.write("</h3>\r\n");
      out.write("   <input class=\"btn btn-success\" type=\"submit\" name=\"ok\" value=\"finish\">  \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("   </form>  \r\n");
      out.write("   <hr>  \r\n");
      out.write("    \r\n");
      out.write("   ");
 
   x++;
   answers.add(request.getParameter("rg"));
   st.setAttribute("answers",answers);
 // String gt=Integer.toString(x);
  //mysession.setAttribute("x",1);
   }

      out.write("\r\n");
      out.write("<form action=\"result.jsp\" name=\"formb\">  \r\n");
      out.write("   <input class=\"btn btn-success\" type=\"submit\" name=\"results\" value=\"show results\" style=\"display:none;\">   \r\n");
      out.write("   </form> \r\n");
      out.write("   ");

  }
   }
 catch(Exception e)
		{	
                e.printStackTrace();
		}
   
   
      out.write("\r\n");
      out.write("   <script>  \r\n");
      out.write("   <!--  \r\n");
      out.write("   timer(); // call timer() after page is loaded  \r\n");
      out.write("   //-->  \r\n");
      out.write("   </script>  \r\n");
      out.write("   </body></html>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
