/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-19 20:58:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_005fup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<HTML>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Online Examination System</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function valid(){\r\n");
      out.write("var fname=f1.t1.value;\r\n");
      out.write("var lname=f1.t2.value;\r\n");
      out.write("var fathername=f1.t3.value;\r\n");
      out.write("var phone=f1.t4.value;\r\n");
      out.write("var address=f1.t5.value;\r\n");
      out.write("var loginid=f1.t6.value;\r\n");
      out.write("var pass=f1.t7.value;\r\n");
      out.write("var cpass=f1.t8.value;\r\n");
      out.write("var email=f1.t9.value;\r\n");
      out.write("var date=f1.datum1.value;\r\n");
      out.write("var cs=f1.d1.value;\r\n");
      out.write("if(fname==\"\"){\r\n");
      out.write("alert(\"Please Fill First_Name\");\r\n");
      out.write("document.f1.t1.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(lname==\"\"){\r\n");
      out.write("alert(\"Please Fill Last_Name\");\r\n");
      out.write("document.f1.t2.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(fathername==\"\"){\r\n");
      out.write("alert(\"Please Fill Father_Name\");\r\n");
      out.write("document.f1.t3.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(phone==\"\"||phone.toString().length<10||isNaN(phone)){\r\n");
      out.write("alert(\"1. Please Fill Phone Number \\n 2. Not less than 10 digit \\n 3. Enter number only\");\r\n");
      out.write("document.f1.t4.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(address==\"\"){\r\n");
      out.write("alert(\"Please Fill Address\");\r\n");
      out.write("document.f1.t5.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(loginid==\"\"){\r\n");
      out.write("alert(\"Please Fill Login Id\");\r\n");
      out.write("document.f1.t6.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(pass==\"\"){\r\n");
      out.write("alert(\"Please Fill Password\");\r\n");
      out.write("document.f1.t7.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(cpass==\"\"||cpass!=pass){\r\n");
      out.write("alert(\"1. Please Fill Confirm Password \\n 2. Password Must Be Same\");\r\n");
      out.write("document.f1.t8.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else if(cs==\"Select Course\"){\r\n");
      out.write("alert(\"Please Select Course \");\r\n");
      out.write("document.f1.d1.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}else{\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"Main\">\r\n");
      out.write("    <form id=\"form1\" name=\"f1\" action=\"st_reg_in\" method=\"POST\" onsubmit=\"return valid()\">\r\n");
      out.write("<div id=\"header-wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("                <li class=\"current_page_item\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"aboutus.jsp\" class=\"first\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"home.jsp\" class=\"first\">Login</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"previousexams.jsp\">Previous Exam</a></li>\r\n");
      out.write("                <li><a href=\"practiceexam.jsp\">Practice Exam</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("                <li><a href=\"help.jsp\" class=\"first\">Help</a></li>\r\n");
      out.write("                <li><a href=\"contactus.jsp\" class=\"first\">Contact Us</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"logo\">\r\n");
      out.write("\t<img src=\"images/logo1.gif\"/>\r\n");
      out.write("\t<h1 style=\"margin:-80px 0 0 60px;\">Online Examination System</h1>\r\n");
      out.write("\t<p style=\"margin:0 0 0 70px;\">Excel your potential</p>\r\n");
      out.write("</div>\r\n");
      out.write("<hr />\r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\t<div id=\"page-bgtop\">\r\n");
      out.write("\t<table style=\"width: 100%\" class=\"fnt_b_12\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td width=\"200\" ></td>\r\n");
      out.write("            <td width=\"150\"></td>\r\n");
      out.write("            <td width=\"10\"></td>\r\n");
      out.write("            <td width=\"230\"></td>\r\n");
      out.write("            <td ></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                First Name<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <input type=\"text\" class=\"txtbox\"  name=\"t1\" id=\"t1\"/>\r\n");
      out.write("                 \r\n");
      out.write("           \r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("            \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                Last Name<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("<input type=\"text\" class=\"txtbox\"  name=\"t2\" id=\"t2\"/>                 \r\n");
      out.write("           \r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        \r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("              </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                Father Name<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("<input type=\"text\" class=\"txtbox\"  name=\"t3\" id=\"t3\"/>                 \r\n");
      out.write("           \r\n");
      out.write("              </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>Phone&nbsp;<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("<input type=\"text\" class=\"txtbox\"  name=\"t4\" id=\"t4\" maxlength=\"10\" />                 \r\n");
      out.write("           \r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                Address<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("<input type=\"text\" class=\"txtbox\"  name=\"t5\" id=\"t5\"/>                 \r\n");
      out.write("           \r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>Login ID<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("<input type=\"text\" class=\"txtbox\"  name=\"t6\" id=\"t6\"/>                 \r\n");
      out.write("           \r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                Password<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("<input type=\"password\" class=\"txtbox\"  name=\"t7\" id=\"t7\"/>                 \r\n");
      out.write("           \r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("              </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                Confirm Password<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <strong>:</strong></td>\r\n");
      out.write("            <td>\r\n");
      out.write("<input type=\"password\" class=\"txtbox\"  name=\"t8\" id=\"t8\"/>                 \r\n");
      out.write("           \r\n");
      out.write("              </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>Email<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("            <td><strong>:</strong></td>\r\n");
      out.write("            <td><input type=\"email\" class=\"txtbox\"  name=\"t9\" id=\"t9\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>&nbsp;</td>\r\n");
      out.write("          <td>Exam Date<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("          <td><strong>:</strong></td>\r\n");
      out.write("          <td><input type=\"date\" class=\"txtbox\"  name=\"datum1\" id=\"datum1\"/></td>\r\n");
      out.write("          <td>&nbsp;</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>&nbsp;</td>\r\n");
      out.write("          <td>Course<span style=\"color: #FF0000\">*</span></td>\r\n");
      out.write("          <td><strong>:</strong></td>\r\n");
      out.write("          <td><label for=\"d1\"></label>\r\n");
      out.write("            <select name=\"d1\" id=\"d1\">\r\n");
      out.write("              <option>Select Course</option>\r\n");
      out.write("              <option value=\"Java\">Java</option>\r\n");
      out.write("              <option value=\"Oracle\">Oracle</option>\r\n");
      out.write("              <option value=\"PHP\">PHP</option>\r\n");
      out.write("            </select></td>\r\n");
      out.write("          <td>&nbsp;</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("            <input type=\"submit\"  name=\"cmdSubmit\" value=\"Submit\" />\r\n");
      out.write("            <input type=\"reset\"  name=\"cmdUpdate\" value=\"Clear\"/>\r\n");
      out.write("            <input type=\"button\"  name=\"cmdCancel\" value=\"Cancel\" id=\"cmdCancel\" onClick=\"javascript:location.href='home.jsp'\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td height=\"20px\">\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                \r\n");
      out.write("</td>\r\n");
      out.write("            <td>&nbsp;\r\n");
      out.write("                </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- end #page -->\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
